# Generated by Django 2.0 on 2019-03-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
