# Generated by Django 2.0 on 2019-03-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_auto_20190317_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
